site/src/components/header/subMenu.js, site/src/styles/theme/dark.js, site/src/styles/theme/light.js
=> style: header sub menu fixup

site/src/HOC/withLoading.js, site/src/components/home/sections/latestBlocks.js, site/src/components/icons/loading.svg, site/src/components/loadings/tableLoading.js, site/src/components/table/body/index.js, site/src/components/table/index.js, site/src/pages/blocks.js
=> feat: loading image for blocks list page

site/src/HOC/withCopy.js
=> feat: new HOC withCopy

site/src/components/list/index.js, site/src/components/loadings/loading.js, site/src/pages/block.js
=> feat: list loading effect

site/src/components/home/sections/index.js, site/src/components/home/sections/latestBlocks.js
=> fix: fix style of home page section loading

site/src/components/block/tabTables/eventsTable.js, site/src/components/block/tabTables/extrinsicsTable.js, site/src/components/pagination/caret.js, site/src/components/pagination/items.js, site/src/components/styled/link.js, site/src/components/styled/panel.js, site/src/components/tab/index.js, site/src/pages/block.js, site/src/pages/blocks.js, site/src/utils/constants.js, site/src/utils/viewFuncs/index.js
=> feat: block detail page tab tables

site/src/App.js, site/src/components/header/index.js, site/src/components/table/head/timeHead.js, site/src/pages/events.js, site/src/utils/constants.js
=> feat: event list page , #76

site/src/App.js, site/src/components/header/index.js, site/src/components/styled/link.js, site/src/pages/accounts.js, site/src/utils/constants.js
=> feat: accounts list page, #86

site/src/components/home/sections/index.js, site/src/components/home/sections/latestBlocks.js, site/src/components/home/sections/latestTransfers.js, site/src/components/home/sections/transfer.svg, site/src/components/home/sections/transferRight.svg, site/src/components/styled/flex.js
=> feat: home latest transfers

site/src/components/header/index.js, site/src/components/header/subMenu.js, site/src/components/styled/divider.js
=> style: header menu divider, #97

site/src/components/home/sections/latestBlocks.js, site/src/components/home/sections/latestTransfers.js, site/src/components/layout/index.js, site/src/components/tooltip/index.js, site/src/components/tooltip/tip.js, site/src/pages/index.js, site/src/store/reducers/index.js, site/src/store/reducers/tooltipSlice.js, site/src/styles/theme/dark.js, site/src/styles/theme/light.js
=> feat: new tooltip component, #96

site/src/components/home/sections/latestTransfers.js
=> fix: latest transfers parse balance

site/src/components/header/chainSwitch/index.js, site/src/utils/constants.js
=> feat: more chain switch

site/src/components/account/tabTables/transfersTable.js, site/src/components/tab/index.js, site/src/components/tooltip/tip.js, site/src/pages/account.js, site/src/utils/constants.js, site/src/utils/viewFuncs/toTableItem.js
=> feat: account tab table for transfers & other chore changes

site/src/App.js, site/src/components/header/index.js, site/src/pages/calls.js, site/src/styles/theme/light.js, site/src/utils/constants.js
=> feat: page calls

site/src/App.js, site/src/pages/call.js, site/src/pages/calls.js
=> feat: page call

site/src/components/call/table.js, site/src/pages/calls.js
=> refactor: extract call table

site/src/components/extrinsic/tabTables/callsTable.js, site/src/pages/extrinsic.js
=> feat: page extinsic calls table

site/src/pages/index.js
=> feat: disable overview for now

site/.env.example, site/src/components/header/chainSwitch/index.js, site/src/utils/constants.js
=> chore: complete config with polkadot, #146

site/src/components/header/index.js, site/src/components/header/subMenu.js
=> fix: header layout

site/src/components/dotBackground.js, site/src/components/header/index.js, site/src/components/layout/index.js, site/src/utils/constants.js
=> fix: mobile missing menu items

site/src/components/dropdown/index.js, site/src/components/header/chainSwitch/index.js, site/src/components/header/index.js, site/src/utils/hooks/index.js
=> refactor: use osn common hooks directly

site/package.json
https://github.com/opensquare-network/common/issues/5
=> build: ignore annoying sourcemap warning

backend/packages/server/src/features/accounts/controllers/transfers.js
=> Fix account transfers count, #183

site/src/pages/extrinsic.js
=> fix: page extrinsic table counts

site/src/components/pagination/caret.js, site/src/components/pagination/index.js
=> fix: pagination caret area

site/src/components/call/callsTable.js, site/src/components/detail/table.js, site/src/pages/extrinsic.js, site/src/services/urls.js, site/src/store/reducers/detailTablesSlice.js, site/src/store/reducers/index.js
=> feat: page extrinsic, tab tables redux

site/src/pages/events.js
=> fix: page events default filter query

site/src/components/address/index.js
=> chore: support copy for <Address> non-ellipsis

site/src/components/block/tabTables/extrinsicsTable.js, site/src/components/detail/table.js, site/src/pages/account.js, site/src/utils/constants.js, site/src/utils/viewFuncs/toTableItem.js
=> feat: add account tab table (extrinsic)

site/src/components/table/body/row/index.js, site/src/utils/constants.js
=> refactor: as `call` type

site/src/pages/event.js, site/src/pages/extrinsic.js
=> fix: page detail breadcrumb

site/src/components/block/tabTables/extrinsicsTable.js, site/src/pages/extrinsics.js
=> chore: clean prs legacy

site/src/components/dropdown/index.js, site/src/components/filter/index.js, site/src/pages/extrinsics.js, site/src/store/reducers/filterSlice.js, site/src/store/reducers/index.js, site/src/utils/hooks/filter.js
=> New filter 235

site/src/pages/block.js, site/src/services/urls.js, site/src/store/reducers/blockSlice.js, site/src/store/reducers/extrinsicSlice.js, site/src/store/reducers/index.js
=> refactor: block reduxlize

site/src/pages/extrinsics.js, site/src/services/urls.js, site/src/store/reducers/extrinsicSlice.js
=> refactor: page extrinsics redux

site/src/pages/accounts.js, site/src/services/urls.js, site/src/store/reducers/accountSlice.js, site/src/store/reducers/index.js
=> refactor: page accounts redux

site/src/pages/accounts.js, site/src/pages/extrinsics.js, site/src/utils/hooks/filter.js
=> fix: missed use effect deps

site/src/pages/calls.js, site/src/services/urls.js, site/src/store/reducers/callSlice.js
=> refactor: page calls redux

site/src/pages/events.js, site/src/services/urls.js, site/src/store/reducers/eventSlice.js
=> refactor: page events redux

site/src/components/home/overview/index.js
=> fix: page home overview item width

site/src/components/input/index.js
=> style: fixup seach box #271

site/public/imgs/icons/default.svg, site/src/components/asset/assetInfo.js, site/src/pages/asset.js
=> feat: asset detail about info

site/src/components/layout/container.js, site/src/utils/constants.js, site/src/utils/viewFuncs/toDetailItem.js
=> style: fixup asset styles

site/package.json, site/src/components/filter/index.js, site/yarn.lock
=> fix: filter layout

site/src/components/filter/index.js, site/src/utils/hooks/extrinsicFilter.js
#234 
revert some changes #345
=> fix: filter layout 2

site/src/components/home/sections/index.js, site/src/components/styled/panel.js, site/src/pages/accounts.js, site/src/pages/assets.js, site/src/pages/blocks.js, site/src/pages/calls.js, site/src/pages/events.js, site/src/pages/extrinsics.js, site/src/pages/transfers.js
=> fix: styled panel table wrapper footer, and it should fixed to the right

site/src/components/home/sections/assets.js, site/src/pages/assets.js, site/src/utils/hooks/useAssetsTableData.js
=> refactor: assets table data hook

site/src/utils/hooks/useAssetsTableData.js
=> fix: assets table total supply tooltip

site/src/components/asset/assetInfo.js, site/src/components/symbol/index.js, site/src/utils/hooks/useAssetInfoData.js
=> fix: assets table symbol icon

backend/packages/server/src/env/index.js, backend/packages/server/src/features/assets/controllers/assets.js, backend/packages/server/src/utils/consts/chains.js, site/src/components/home/sections/assets.js, site/src/components/home/sections/index.js, site/src/components/home/sections/latestBlocks.js, site/src/components/home/sections/latestTransfers.js, site/src/services/websocket/index.js, site/src/store/reducers/socketSlice.js
- Improve blocks/transfers loading check
- Fetch assets by holders desc sort
=> Refactor home page sections

site/src/components/charts/assetAnalytics/body.js
=> fix: page asset analytics loading, animation

site/src/components/home/sections/latestBlocks.js
=> fix: home latest blocks item half width

site/src/components/home/sections/latestBlocks.js
=> fix: home latest blocks item container

site/src/components/detail/tabs.js, site/src/pages/account.js, site/src/pages/asset.js, site/src/pages/block.js, site/src/pages/extrinsic.js, site/src/utils/constants.js
=> feat: page detail persist tab

site/src/components/detail/tabs.js
=> fix: page detail tabs scroll

site/src/pages/asset.js, site/src/store/reducers/assetSlice.js
=> fix: reset asset detail redux data on page leave

site/src/components/list/index.js, site/src/pages/asset.js, site/src/pages/block.js, site/src/pages/call.js, site/src/pages/event.js
=> fix: page detail loading

site/src/pages/account.js
=> fix: page account breadcrumb

site/src/services/websocket/index.js
=> fix: page home latest panels, move set loading

site/src/components/address/identity.js, site/src/components/home/sections/latestTransfers.js
=> fix: home latest transfer identity size

site/src/components/footer/index.js, site/src/components/header/index.js, site/src/components/layout/home.js
=> fix: layout align

site/src/pages/account.js, site/src/utils/constants.js, site/src/utils/viewFuncs/toTableItem.js
=> feat: account assets tab

site/src/components/header/subMenu.js
=> fix: header, increase menu dropdown layer

site/src/App.js, site/src/pages/destroyed/assets.js, site/src/utils/constants.js, site/src/utils/hooks/useAssetsTableData.js
=> feat: destroyed assets list

site/src/services/urls.js
=> refactor: urls no `make` fns

site/src/components/header/navi/index.js, site/src/components/header/subMenu.js, site/src/utils/constants.js
=> fix: mobile nav assets menu entry

site/src/components/header/index.js, site/src/utils/hooks/useScrollLock.js
=> fix: mobile navigation lock body scroll

site/src/components/header/subMenu.js, site/src/components/layout/index.js
=> fix: layout main layer level

site/src/components/tag/index.js, site/src/styles/theme/dark.js, site/src/styles/theme/light.js, site/src/utils/viewFuncs/toDetailItem.js
=> feat: asset detail status tag

site/src/components/symbol/index.js
=> fix: symbol link destroyed prop

site/src/components/footer/producer.js
=> fix: footer css effected by semantic ui

site/src/pages/assets.js
=> fix: clean assets list on page leave

site/src/styles/tailwindcss.js
old file, better way to write any styles in styled-component
=> feat: tailwindcss atomic css modules

site/src/components/address/identity.js
=> fix: address identity icon align

site/src/components/home/sections/index.js, site/src/pages/index.js
=> fix: home layout gap margin

site/src/components/charts/assetAnalytics/index.js, site/src/pages/asset.js, site/src/store/reducers/assetSlice.js
=> feat: cache asset analytics data

site/src/components/home/explore/dropdown.js, site/src/components/home/explore/input.js, site/src/components/home/explore/utils.js, site/src/utils/viewFuncs/text.js
=> feat: nft explore input

site/src/components/home/explore/dropdown.js
=> fix: explore, fixed nft thumbnail size to 24

site/src/components/table/head/timeHead.js
=> fix: table time header ui

site/src/components/home/sections/index.js
=> fix: home sections layout

site/src/components/filter/index.js, site/src/components/footer/socialMedia.js, site/src/components/header/subMenu.js, site/src/components/home/explore/index.js, site/src/components/home/sections/index.js, site/src/components/icons/caret-down.svg, site/src/components/styled/buttons/index.js, site/src/components/symbol/symbolLink.js, site/src/styles/tailwindcss.js, site/src/styles/theme/light.js, site/src/utils/hooks/useAssetsTableData.js
=> fix: ui (#552)

site/src/pages/transfers.js, site/src/utils/hooks/transfersFilter.js
=> feat: transfer filter

site/src/pages/calls.js, site/src/utils/hooks/callsFilter.js
=> feat: calls filter

site/src/utils/hooks/callsFilter.js, site/src/utils/hooks/eventFilter.js, site/src/utils/hooks/extrinsicFilter.js
=> fix: filter section string cases

site/src/HOC/withLoading.js, site/src/components/table/body/index.js, site/src/components/table/index.js
close #554 , now the icon fixed in center and can not scroll if is loading
=> Fix with loading

site/src/components/home/sections/latestTransfers.js
=> fix: signed transfers item layout

site/src/components/home/sections/latestTransfers.js
=> fix: signed transfers layout

site/src/components/dataDisplay/index.js, site/src/components/extrinsicParametersDisplay.js, site/src/components/table/nestedTable/innerTable.js, site/src/pages/call.js, site/src/pages/extrinsic.js
=> feat: no parameters, fix ui

site/src/HOC/withLoading.js, site/src/components/home/sections/index.js, site/src/components/home/sections/latestBlocks.js, site/src/components/home/sections/latestTransfers.js, site/src/components/loadings/loading.js, site/src/components/noData.js
=> fix: home section empty status, and css

site/src/components/displayValue.js
revert this line
https://github.com/opensquare-network/statescan-v2/pull/578/files#diff-5accbbc4cefa8fdcc8a15007b2b4d8d377f743ac53ccbcf1321736c3e4e27236R64
=> hotfix: revert value display decimal

site/src/components/home/sections/latestTransfers.js, site/src/components/transfer/list/row.js
=> feat: transfer list symbol link to asset detail

site/src/components/header/index.js, site/src/components/home/explore/dropdown.js
=> fix: explore input css

site/src/components/table/head/index.js
=> hotfix: table head `calls` width

site/src/components/home/sections/index.js, site/src/components/home/sections/latestList.js
=> fix: latest view all fixed to bottom

site/package.json, site/src/components/table/head/index.js, site/yarn.lock
=> hotfix: detail table width

site/src/components/filter/index.js, site/src/pages/events.js, site/src/utils/constants.js, site/src/utils/hooks/eventFilter.js
=> Fix: update events filters and filters layout

site/src/utils/constants.js, site/src/utils/hooks/useAssetsTableData.js
=> feat: add height to destroyed assets table

site/src/utils/hooks/useAssetsTableData.js
=> fix: destroyed assets table align

site/src/components/home/sections/governance.js
=> fix: governance items

site/src/components/home/explore/dropdown.js
=> hotfix: explorer dropdown item width

site/src/pages/accounts.js, site/src/pages/blocks.js, site/src/pages/calls.js, site/src/pages/events.js, site/src/pages/extrinsics.js
=> hotfix: clear list data logic

site/src/components/address/identity.js, site/src/components/address/index.js, site/src/components/extrinsicAssetsTransferredList.js, site/src/components/list/index.js, site/src/components/nft/thumbnail/index.js, site/src/pages/extrinsic.js, site/src/services/urls.js, site/src/styles/tailwindcss.js, site/src/utils/nft.js, site/src/utils/viewFuncs/toDetailItem.js
=> feat: extrinsic assets transferred

site/src/components/nft/thumbnail/index.js
=> hotfix: nft list class image height

site/package.json
=> build: add pkg overrides for react-json-view

site/src/components/table/head/index.js, site/src/utils/constants.js
=> feat: table support min width

site/src/components/nft/thumbnail/index.js
=> fix: Improve NFT small logo, #812

.github/workflows/ci.yml, .github/workflows/site-ci.yml
=> ci: improve for site

site/src/components/nodeSwitch/index.js
=> fix: node switch button outline, #825

site/src/components/home/explore/dropdown.js
(cherry picked from commit 3a825596dbc91f9d8820a22465492e8847647170)
=> fix: update style

site/src/components/header/mobileNodeSwitch/index.js
(cherry picked from commit cd53afbddeaaa867484891d99522844f6c8c0b85)
=> fix: empty judgment

site/package.json, site/src/components/address/index.js, site/src/components/home/explore/dropdown.js, site/src/components/home/explore/input.js, site/src/components/home/explore/utils.js, site/yarn.lock
=> fix: explore identities arrow navigation

site/.env.example, site/src/App.js, site/src/components/vestings/table.jsx, site/src/hooks/apollo.js, site/src/hooks/filter/useVestingsFilter.jsx, site/src/pages/vestings.jsx, site/src/services/gqls.js, site/src/utils/chain/index.js, site/src/utils/constants.js, site/src/utils/consts/chains/kusama.js, site/src/utils/consts/chains/polkadot.js, site/src/utils/consts/menu.js
=> feat: vestings

site/src/components/layout/index.js, site/src/components/vestings/table.jsx, site/src/pages/index.js
=> fix: vestings latest height

site/src/components/multisig/table.jsx
=> feat: multisigs approving cell improvement

site/src/components/header/chainSwitch/index.js, site/src/components/header/mobileNodeSwitch/index.js, site/src/components/header/styled.js
=> fix: header dropdown layout

site/src/components/multisig/timeline.jsx, site/src/pages/multisig.jsx
=> hotfix: multisig detail

backend/packages/common/src/utils/isValidAddress.js, backend/packages/graphql-server/src/schema/chain/resolvers/account.js, backend/packages/graphql-server/src/schema/chain/resolvers/getAccount/index.js, backend/packages/server/src/features/blocks/controllers/latestBlocks.js, backend/packages/server/src/features/blocks/routes.js, backend/packages/server/src/features/overview/routes.js, backend/packages/server/src/features/search/controllers/hints/account.js, backend/packages/server/src/features/transfers/controllers/latestTransfers.js, backend/packages/server/src/features/transfers/routes.js, backend/packages/server/src/routes.js
=> Add overview api and fix account search API, 925

site/src/pages/extrinsic/detailTabs.jsx, site/src/pages/extrinsic/onChainExtrinsic.jsx
- add loading states for panels Events/Calls
- refactor OnChainExtrinsic component
=> Add loading states for panels Events/Calls on extrinsics detail, #1129
